# Generated by Django 5.2.5 on 2025-08-10 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrammarExemple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exemple', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrammarImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='grammar_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('descriptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grammardescriptions')),
                ('exemple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grammarexemple')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grammarimg')),
            ],
        ),
    ]
