# Generated by Django 5.2.5 on 2025-08-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammardescriptions',
            name='name_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grammarexemple',
            name='name_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grammarimg',
            name='name_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
