# Generated by Django 5.2.5 on 2025-08-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_grammardescriptions_name_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='exemple',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='picture',
        ),
        migrations.AddField(
            model_name='grammar',
            name='descriptions',
            field=models.ManyToManyField(blank=True, to='app.grammardescriptions'),
        ),
        migrations.AddField(
            model_name='grammar',
            name='exemple',
            field=models.ManyToManyField(blank=True, to='app.grammarexemple'),
        ),
        migrations.AddField(
            model_name='grammar',
            name='picture',
            field=models.ManyToManyField(blank=True, to='app.grammarimg'),
        ),
    ]
