# Generated by Django 5.2.5 on 2025-08-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_grammar_descriptions_remove_grammar_exemple_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iregulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(blank=True, max_length=100, verbose_name='Base form (present)')),
                ('past', models.CharField(blank=True, max_length=50, verbose_name='past simple')),
                ('pp', models.CharField(blank=True, max_length=50, verbose_name='Past Participle')),
                ('translation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Translation')),
                ('example', models.TextField(blank=True, null=True, verbose_name='Example sentence')),
            ],
        ),
    ]
