# Generated by Django 5.2.5 on 2025-08-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_iregulars'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grammar',
            table='grammar',
        ),
        migrations.AlterModelTable(
            name='grammardescriptions',
            table='grammarDescriptions',
        ),
        migrations.AlterModelTable(
            name='grammarexemple',
            table='grammarExemple',
        ),
        migrations.AlterModelTable(
            name='grammarimg',
            table='GrammarImg',
        ),
        migrations.AlterModelTable(
            name='iregulars',
            table='iregulars',
        ),
    ]
